"""Set ondelete=SET NULL on Creation.item_id

Revision ID: 6636ba22edd9
Revises: d99a110dbab6
Create Date: 2025-07-11 06:58:56.892267

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6636ba22edd9'
down_revision = 'd99a110dbab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('creation_item_id_fkey', 'creation', type_='foreignkey')
    op.create_foreign_key(None, 'creation', 'item', ['item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'creation', type_='foreignkey')
    op.create_foreign_key('creation_item_id_fkey', 'creation', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###
