"""Add created_at to Item

Revision ID: d99a110dbab6
Revises: 1816904b6647
Create Date: 2025-07-11 05:21:22.947687

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd99a110dbab6'
down_revision = '1816904b6647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creation', sa.Column('item_id', sa.Uuid(), nullable=True))
    op.alter_column('creation', 'youtube_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('creation', 'timestamp_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('creation', 'input_video_keys',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('creation', 'input_audio_keys',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_constraint('creation_owner_id_fkey', 'creation', type_='foreignkey')
    op.create_foreign_key(None, 'creation', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'creation', 'item', ['item_id'], ['id'])
    op.add_column('item', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('item', 'chat_history',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'chat_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_column('item', 'created_at')
    op.drop_constraint(None, 'creation', type_='foreignkey')
    op.drop_constraint(None, 'creation', type_='foreignkey')
    op.create_foreign_key('creation_owner_id_fkey', 'creation', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('creation', 'input_audio_keys',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('creation', 'input_video_keys',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('creation', 'timestamp_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('creation', 'youtube_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('creation', 'item_id')
    # ### end Alembic commands ###
